# Generated by Django 3.1.14 on 2022-11-06 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis_entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='court',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.tempentityclass')),
                ('alternative_label', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Hof', 'Hof'), ('Klosterhof', 'Klosterhof'), ('Kaiserhof', 'Kaiserhof'), ('Königshof', 'Königshof'), ('Bischöflicher Hof', 'Bischöflicher Hof'), ('Kurfürstlicher Hof', 'Kurfürstlicher Hof'), ('Erzbischöflicher Hof', 'Erzbischöflicher Hof'), ('Königlicher Hof', 'Königlicher Hof'), ('Kaiserlicher Hof', 'Kaiserlicher Hof'), ('Frauenzimmer', 'Frauenzimmer')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.tempentityclass')),
                ('alternative_label', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Hochzeit', 'Hochzeit'), ('Landtag', 'Landtag'), ('Fest/Turnier', 'Fest/Turnier'), ('Schlacht', 'Schlacht'), ('Gesandtschaft/Reise', 'Gesandtschaft/Reise'), ('Taufe', 'Taufe'), ('Amtseinsetzung', 'Amtseinsetzung'), ('Reichstag', 'Reichstag')], max_length=19)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='function',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.tempentityclass')),
                ('alternative_label', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='institution',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.tempentityclass')),
                ('alternative_label', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Kanzlei', 'Kanzlei'), ('Hofkapelle', 'Hofkapelle'), ('Küche', 'Küche'), ('(Dom-)Kapitel', '(Dom-)Kapitel'), ('Universität', 'Universität'), ('Kloster', 'Kloster'), ('Frauenzimmer', 'Frauenzimmer'), ('Bistum', 'Bistum'), ('Pfarrei', 'Pfarrei')], max_length=13)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.tempentityclass')),
                ('first_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('gender', models.CharField(blank=True, choices=[('männlich', 'männlich'), ('weiblich', 'weiblich'), ('unbekannt', 'unbekannt')], max_length=9)),
                ('class_affiliation', models.CharField(blank=True, choices=[('Hoher Adel', 'Hoher Adel'), ('Niederer Adel', 'Niederer Adel'), ('Klerus', 'Klerus'), ('Bürgertum', 'Bürgertum'), ('Bauerntum', 'Bauerntum'), ('Gesinde', 'Gesinde')], max_length=13)),
                ('alternative_label', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.tempentityclass')),
                ('alternative_label', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Stadt', 'Stadt'), ('Dorf', 'Dorf'), ('Burg', 'Burg'), ('Land/Herrschaftskomplex', 'Land/Herrschaftskomplex'), ('Landschaft/Region', 'Landschaft/Region')], max_length=23)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('tempentityclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis_entities.tempentityclass')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=1024, null=True)),
                ('repetitions', models.IntegerField(blank=True, null=True)),
                ('repetition_note', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('einfach', 'einfach'), ('wiederholend', 'wiederholend')], max_length=12)),
            ],
            options={
                'abstract': False,
            },
            bases=('apis_entities.tempentityclass',),
        ),
    ]
