# Generated by Django 3.1.14 on 2022-12-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='class_affiliation',
        ),
    ]
