name: deploy
on:
  push:
    branches: [main]
    tags:
      - deploy
      - deploy.*
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  deploy:
    uses: acdh-oeaw/prosnet-workflows/.github/workflows/deploy-apis-instance.yml@v0.3.1
    secrets: inherit
